### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by delightfulabyss** [0xPrimordia/impact-stream-pwa#190]
- [ ] Configure production domain for Privy
- [ ] Add profile data to IPFS
- [ ] Add pool data to IPFS
- [ ] Add recipient data to IPFS
- [ ] Deploy voting token contract
- [ ] Add Profiles to project registry
- [ ] Encode QF strategy init data
- [ ] Call createPool on Allo contract
- [ ] Run Safe creation script
- [ ] Airdrop users 5 (?) tokens
